-------------------------------------------------------------------------------
--  NaowhUI_SmartReminders_CuratedAbilities.lua -- which journal abilities
--  BigWigs/LittleWigs itself tracks per boss, grouped by fight phase.
--
--  GENERATED by Tools/extract_curated_abilities.py. Regenerate rather than
--  hand-editing.
--
--  Names, icons and descriptions still come from the player's own Dungeon Journal
--  at runtime (NaowhUI_SmartReminders_Bosses.lua) -- this file supplies only which
--  spellIDs matter and how BigWigs/LittleWigs itself groups them by phase, read
--  from their own boss modules (raid and current-tier dungeons from BigWigs,
--  older Mythic+ pool dungeons from LittleWigs -- same project, same team). Used
--  with permission (Funkeh, BigWigs developer).
--
--  Bosses with no entry here fall back to the full journal listing.
-------------------------------------------------------------------------------
local ns = _G.NaowhUITankReminder
if not ns then return end

ns.CURATED_ABILITIES = {
	[3182] = { -- Belo'ren, Child of Al'ar
		{ phase = "Phase 1", abilities = { 1242515, 1241282, 1241292, 1242981, 1260763, 1244344, 1242260, 1246709 } },
		{ phase = "Phase 2", abilities = { 1241313 } },
	},
	[3183] = { -- Midnight Falls
		{ phase = "Phase 1", abilities = { 1253915, 1279420, 1249620, 1249609, 1251386, 1267049 } },
		{ phase = "Intermission", abilities = { 1282441, 1282469 } },
		{ phase = "Phase 2", abilities = { 1284525, 1282412, 1281194 } },
		{ phase = "Phase 3", abilities = { 1250898, 1266388, 1266897 } },
		{ phase = "Mythic", abilities = { 1284980, 1284931 } },
		{ phase = "Mythic", abilities = { 1273158, 1276525 } },
	},
	[3379] = { -- Nymrissa Wavecaller
		{ phase = "General", abilities = { 1276710, 1257717, 1257608, 1258668, 1260837, 1282937, 1313393 } },
		{ phase = "Mythic", abilities = { 1268562 } },
	},
	[3159] = { -- Rotmire
		{ phase = "General", abilities = { 1221622, 1221637, 1222088, 1221787, 1221781 } },
	},
	[3306] = { -- Chimaerus the Undreamt God
		{ phase = "Phase One: Insatiable Hunger", abilities = { 1262289, 1258610, 1257087, 1246653, 1272726, 1245396 } },
		{ phase = "Phase Two: To The Skies", abilities = { 1245486, 1245406, 1246621, 1257085 } },
		{ phase = "Mythic", abilities = { 1264756 } },
	},
	[3429] = { -- The Coiled Altar
		{ phase = "Phase One: Serpent's Bargain", abilities = { 1282487, 1299960, 1283489, 1299680, 1282281, 1283832 } },
		{ phase = "Phase Two: Usurper's Reprisal", abilities = { 1289900, 1285911, 1286573, 1286918, 1286441, 1286895 } },
		{ phase = "Zul'jan", abilities = { 1298381 } },
		{ phase = "Toxic Deluge", abilities = { 1299266, 1307279 } },
	},
	[3497] = { -- The Lost Explorers
		{ phase = "Mor'zahi", abilities = { 1296535, 1297022, 1292779 } },
		{ phase = "Scrollsage Iku", abilities = { 1290711, 1286921, 1295854, 1295886, 1291390 } },
		{ phase = "First Mate Nama", abilities = { 1291759, 1296092 } },
		{ phase = "Trader Gebbo", abilities = { 1291933, 1295817, 1292104, 1296249 } },
	},
	[3470] = { -- Nek'zali the Soulcoiler
		{ phase = "Phase One: Soulcoiler Initiation", abilities = { 1285681, 1287426, 1295397, 1287533, 1292036 } },
		{ phase = "Intermission: Ritual of Awakening", abilities = { 1305421 } },
		{ phase = "Phase Two: Uncoiling", abilities = { 1299673 } },
		{ phase = "Mythic", abilities = { 1293212 } },
	},
	[3445] = { -- Entombed Sentinels
		{ phase = "General", abilities = { 1284588 } },
		{ phase = "Vashnik the Malignant (Mythic)", abilities = { 1296878 } },
		{ phase = "Breath of Ula'tek", abilities = { 1284251, 1284434, 1284458 } },
		{ phase = "Blood of Ula'tek", abilities = { 1284483, 1288232, 1284487 } },
	},
	[3420] = { -- Sszorak
		{ phase = "General", abilities = { 1285732, 1277025, 1305959, 1285425 } },
		{ phase = "Mythic", abilities = { 1296898 } },
	},
	[3421] = { -- The Twin Fangs
		{ phase = "General", abilities = { 1308556 } },
		{ phase = "Vexhul", abilities = { 1289192, 1291404, 1291478, 1290956, 1294293 } },
		{ phase = "Ithraz", abilities = { 1303230, 1308356, 1290516, 1290809, 1288538, 1306872 } },
	},
	[3492] = { -- Ula'tek
		{ phase = "Phase One: Fury of the Serpent Mother", abilities = { 1292188, 1300751, 1298367, 1298559, 1296301, 1300530, 1286860 } },
		{ phase = "Phase Two: Children of the Doomscale", abilities = { 1302982 } },
		{ phase = "Phase Three: Ula'tek's Ascension", abilities = { 1301510, 1292999 } },
		{ phase = "Call of the Serpent", abilities = { 1295905 } },
		{ phase = "Rage of the Shackled", abilities = { 1286905 } },
	},
	[3455] = { -- Vashnik the Malignant
		{ phase = "General", abilities = { 1283164 } },
	},
	[3176] = { -- Imperator Averzian
		{ phase = "General", abilities = { 1251361, 1262036, 1249262, 1280015, 1260712, 1258883, 1249251 } },
	},
	[3181] = { -- Crown of the Cosmos
		{ phase = "Phase One: The Void's Spire", abilities = { 1233602, 1232467, 1255368, 1233865, 1233787, 1243743, 1243753 } },
		{ phase = "Intermission: Crushing Singularity", abilities = { 1243982 } },
		{ phase = "Phase Two: The Severed Rift", abilities = { 1237614, 1237038, 1237837, 1246918, 1246461, 1261016 } },
		{ phase = "Phase Three: The End of the End", abilities = { 1238843, 1239080, 1261339 } },
	},
	[3179] = { -- Fallen-King Salhadaar
		{ phase = "General", abilities = { 1247738, 1246175, 1250803, 1254081, 1248697, 1250686 } },
	},
	[3178] = { -- Vaelgor & Ezzorak
		{ phase = "General", abilities = { 1249748, 1280458 } },
		{ phase = "Vaelgor", abilities = { 1262623, 1244672, 1244221, 1265131 } },
		{ phase = "Ezzorak", abilities = { 1245391, 1244917, 1245645 } },
	},
	[3180] = { -- Lightblinded Vanguard
		{ phase = "Commander Venel Lightblood", abilities = { 1248449, 1248983, 1246765, 1246749, 1246736 } },
		{ phase = "General Amias Bellamy", abilities = { 1246162, 1248644, 1246485, 1251857 } },
		{ phase = "War Chaplain Senn", abilities = { 1248451, 1248710, 1255738, 1248674 } },
		{ phase = "Mythic", abilities = { 1276243 } },
	},
	[3177] = { -- Vorasius
		{ phase = "General", abilities = { 1256855, 1254199, 1241692, 1260052 } },
	},
	[2140] = { -- The Council of Tribes
		{ phase = "Kula the Butcher", abilities = { 266206, 266231 } },
		{ phase = "Aka'ali the Conqueror", abilities = { 266951, 266237 } },
		{ phase = "Zanazal the Wise", abilities = { 267273, 267060 } },
	},
	[2143] = { -- Dazar, The First King
		{ phase = "General", abilities = { 268586, 268932, 268403, 269231, 269369 } },
	},
	[2139] = { -- The Golden Serpent
		{ phase = "General", abilities = { 265773, 265923, 265781, 265910 } },
	},
	[2142] = { -- Mchimba the Embalmer
		{ phase = "General", abilities = { 267639, 267618, 267702 } },
	},
	[2124] = { -- Adderis and Aspix
		{ phase = "General", abilities = { 263246, 263257, 263371, 263424, 263309 } },
	},
	[2127] = { -- Avatar of Sethraliss
		{ phase = "General", abilities = { 268024, 274149, 269688, 269686, 268008, 268007 } },
	},
	[2126] = { -- Galvazzt
		{ phase = "General", abilities = { 266923, 266512 } },
	},
	[2125] = { -- Merektha
		{ phase = "General", abilities = { 263912, 263927, 263914, 264239, 264206, 263958 } },
	},
	[2606] = { -- Kokia Blazehoof
		{ phase = "Kokia Blazehoof", abilities = { 372863, 372107, 372858 } },
		{ phase = "Blazebound Firestorm", abilities = { 373017, 373087 } },
	},
	[2623] = { -- Kyrakka and Erkhart Stormvein
		{ phase = "Kyrakka", abilities = { 381862, 381525, 381602 } },
		{ phase = "Erkhart Stormvein", abilities = { 381517, 381516, 381512 } },
	},
	[2609] = { -- Melidrussa Chillworn
		{ phase = "General", abilities = { 373046, 372682, 372851, 396044, 372988, 373680 } },
	},
	[3101] = { -- Kystia Manaheart
		{ phase = "General", abilities = { 1253811, 1264095, 474240, 1230304 } },
	},
	[3105] = { -- Lithiel Cinderfury
		{ phase = "General", abilities = { 474408, 1218203, 1224478 } },
	},
	[3103] = { -- Xathuux the Annihilator
		{ phase = "General", abilities = { 473898, 1214637, 1295453, 474197 } },
	},
	[3102] = { -- Zaen Bladesorrow
		{ phase = "General", abilities = { 474478, 474765, 1214357, 1222795, 1218347 } },
	},
	[3209] = { -- Nalorakk Den
		{ phase = "General", abilities = { 1242860, 1243569, 1243011 } },
	},
	[3208] = { -- Sentinel of Winter
		{ phase = "General", abilities = { 1235548, 1235623, 1235783, 1235656 } },
	},
	[3207] = { -- The Hoardmonger
		{ phase = "General", abilities = { 1235118, 1253268, 1234233 } },
	},
	[3200] = { -- Ikuzz the Light Hunter
		{ phase = "General", abilities = { 1236746, 1236709, 1237090 } },
	},
	[3199] = { -- Lightblossom Trinity
		{ phase = "General", abilities = { 1234753, 1235640, 1234850, 1235564 } },
	},
	[3201] = { -- Lightwarden Ruia
		{ phase = "General", abilities = { 1239882, 1239824, 1240098, 1239885, 1241058, 1240210, 1239883 } },
	},
	[3202] = { -- Ziekket
		{ phase = "General", abilities = { 1246372, 1246858, 1247685, 1246607 } },
	},
	[3286] = { -- Atroxus
		{ phase = "General", abilities = { 1222642, 1226120, 1222721, 1262497, 1222371 } },
	},
	[3287] = { -- Charonus
		{ phase = "General", abilities = { 1282770, 1227264, 1263982, 1311923, 1222755 } },
	},
	[3285] = { -- Taz'Rah
		{ phase = "General", abilities = { 1222098, 1296963, 1297017, 1300259 } },
	},
	[3456] = { -- Rav'i
		{ phase = "General", abilities = { 1296220, 1307703, 1296216, 1296050, 1307894 } },
	},
	[3457] = { -- The Writhing Coil
		{ phase = "The Writhing Coil (Stage 1)", abilities = { 1299154, 1298949, 1310357, 1310547, 1299940, 1299130, 1300044, 1299053 } },
		{ phase = "The Uncoiled Writhe (Stage 2)", abilities = { 1310358, 1300686 } },
	},
	[3458] = { -- Zul'jan
		{ phase = "General", abilities = { 1300876, 1301111, 1301350, 1301413 } },
	},
}
