-------------------------------------------------------------------------------
--  NaowhUI_SmartReminders_DungeonQuestData.lua -- every dungeon quest on WoW Forever, from
--  Wowhead's Forever dungeon quest guide (patch 1.60.1, updated 2026-09-23). Generated;
--  instance IDs are the Map table's for build 1.60.1.69913.
--
--  Each quest: { questID, name, level, side ("A", "H" or "B"), shareable (true,
--  false or "pre" for a prerequisite chain), where it starts }.
-------------------------------------------------------------------------------
local ns = _G.NaowhUITankReminder

ns.DungeonQuests = {
    { name = "Ragefire Chasm", map = 389, quests = {
        { 5761, "Slaying the Beast", 9, "H", true, "Orgrimmar, The Drag - Neeru Fireblade (49, 50)" },
        { 5725, "The Power to Destroy...", 9, "H", true, "Undercity, Royal Quarter - Varimathras (56, 92)" },
        { 5723, "Testing an Enemy's Strength", 9, "H", true, "Thunder Bluff, Elder Rise - Rahauro (70, 30)" },
        { 5722, "Searching for the Lost Satchel", 9, "H", true, "Inside RFC - Grimtotem Satchel drop from Maur Grimtotem" },
        { 5728, "Hidden Enemies", 9, "H", "pre", "Orgrimmar, Valley of Wisdom - Thrall Prerequisite: Complete 3 quests, starting with Hidden Enemies from Thrall (31, 37)" },
    } },
    { name = "The Hall of Thanes", map = 3065, quests = {
        { 96403, "Important Heirlooms", 14, "A", true, "Ironforge, Old Ironforge - Thom Filch (32.6, 44.6)" },
        { 96394, "The Restless Dead", 15, "A", true, "Ironforge, Old Ironforge - Afadra Dunwall (64.8, 58.4)" },
        { 96393, "Old Ironforge Incursion", 15, "A", true, "Dun Morogh, Gol'Golar Quarry - Earthseer Farsen Prerequisite to pick up Underground Map from Dark Iron Map (64.8, 58.4)" },
        { 98423, "The Treaty of Understanding", 16, "A", false, "The Hall of Thanes, Located in the Reliquary of Kings in a Vault" },
        { 96395, "An Ancient Grudge", 14, "H", true, "The Hall of Thanes, Anvilmar's Rest - Ghostly Attendant" },
    } },
    { name = "Wailing Caverns", map = 43, quests = {
        { 962, "Serpentbloom", 14, "H", true, "Thunder Bluff, Pools of Vision - Apothecary Zamah (34, 21)" },
        { 1491, "Smart Drinks", 13, "B", "pre", "The Barrens, Ratchet - Mebok Mizzyrix Complete Raptor Horns from same NPC first (62, 37)" },
        { 959, "Trouble at the Docks", 14, "B", true, "The Barrens, Ratchet- Crane Operator Bigglefuzz (63, 37)" },
        { 1486, "Deviate Hides", 13, "B", true, "The Barrens, Above WC entrance - Nalpak (46, 35)" },
        { 1487, "Deviate Eradication", 15, "B", true, "The Barrens, Above WC entrance - Ebru (46, 35)" },
        { 6981, "The Glowing Shard", 10, "B", false, "Wailing Caverns, Drops from Mutanus the Devourer" },
        { 914, "Leaders of the Fang", 15, "H", "pre", "Thunder Bluff, Elder Rise - Nara Wildmane Prerequisite: Complete 5 quests, starting with The Forgotten Pools, The Barrens, Crossroads, Tonga Runetotem (45, 23)" },
    } },
    { name = "The Deadmines", map = 36, quests = {
        { 168, "Collecting Memories", 14, "A", true, "Stormwind, Dwarven District - Wilder Thistlenettle (65, 21)" },
        { 167, "Oh Brother. . .", 15, "A", true, "Stormwind, Dwarven District - Wilder Thistlenettle (65, 21)" },
        { 2040, "Underground Assault", 15, "A", true, "Stormwind, Dwarven District - Shoni the Shilent (55, 13)" },
        { 373, "The Unsent Letter", 16, "A", false, "The Deadmines, drop from Edwin VanCleef Prerequisite to pick up The Stockade Riots" },
        { 214, "Red Silk Bandanas", 14, "A", "pre", "Westfall, Sentinel Hill - Scout Riell Complete 6 quests, starting with The Defias Brotherhood, Gryan Stoutmantle, Sentinell Hill, Westfall (56, 47)" },
        { 166, "The Defias Brotherhood", 14, "A", "pre", "Westfall, Sentinel Hill- Gryan Stoutmantle Same prerequisites as Red Silk Bandanas (56, 47)" },
        { 1654, "The Test of Righteousness", 20, "A", "pre", "[icon name=class_paladin]Paladin Only[/icon] - Ironforge, inside Gates - Jordan Stilwell Starts with Tome of Valor quest chains; starts in different places depending on race. See Paladin Quest guide below. (52, 36)" },
    } },
    { name = "Ruins of Lordaeron", map = 2999, quests = {
        { 92401, "A Frightened Request", 15, "H", true, "Undercity, Tabitha Heartweaver (34, 21)" },
        { 92422, "The Wrath of Rath'mael", 15, "H", true, "Brill, Deathguard Kristof" },
        { 95216, "The New Plague", 16, "H", true, "Undercity,Theodore Griffs (47, 72.6)" },
        { 92421, "Light's Justice", 15, "H", true, "Undercity, Morbin Lightbane (57.8, 89.8)" },
        { 97288, "Unending Torment", 15, "H", true, "Inside Dungeon" },
        { 95250, "Abominable Creatures", 16, "A", false, "TBD" },
        { 95195, "Bloodied Insignia", 16, "A", false, "Stormwind City General Marcus Jonathan" },
        { 92415, "Remember That I Love You", 15, "A", false, "TBD" },
    } },
    { name = "Shadowfang Keep", map = 33, quests = {
        { 1013, "The Book of Ur", 16, "H", true, "Undercity, Apothecarium - Keeper Bel'dugur (53, 54)" },
        { 1098, "Deathstalkers in Shadowfang", 18, "H", true, "Silverpine Forest, Sepulcher - High Executor Hadrec (43, 41)" },
        { 1014, "Arugal Must Die", 18, "H", true, "Silverpine Forest, Sepulcher - Dalar Dawnweaver (44, 39)" },
        { 1740, "The Orb of Soran'ruk", 20, "B", true, "[icon name=class_warlock]Warlock Only[/icon] The Barrens, Near Camp Taurajo - Doan Karhan /49 57" },
        { 1654, "The Test of Righteousness", 20, "A", "pre", "[icon name=class_paladin]Paladin Only[/icon] - Ironforge, inside Gates - Jordan Stilwell Starts with Tome of Valor quest chains; starts in different places depending on race. See Paladin Quest guide below. (52, 36)" },
    } },
    { name = "Blackfathom Deeps", map = 48, quests = {
        { 6563, "The Essence of Aku'Mai", 17, "H", true, "Ashenvale, Zoram'gar Outpost - Je'neu Sancrea (11, 34)" },
        { 6561, "Blackfathom Villainy", 18, "H", true, "Blackfathom Deeps, Alcove SW of Ghamoo-ra - Argent Guard Thaelrid" },
        { 6921, "Amongst the Ruins", 21, "H", true, "Ashenvale, Zoram'gar Outpost - Je'neu Sancrea Summons Baron Aquanis when Fathom Core picked up, needed for next quest (11, 34)" },
        { 6922, "Baron Aquanis", 21, "H", false, "Strange Water Globe, drops from Baron Aquanis" },
        { 1740, "The Orb of Soran'ruk", 20, "B", true, "[icon name=class_warlock]Warlock Only[/icon] The Barrens, Near Camp Taurajo - Doan Karhan /49 57" },
        { 6565, "Allegiance to the Old Gods", 17, "H", false, "Damp Note, low drop rate item from Blackfathom Tide Priestess outside instance" },
        { 971, "Knowledge in the Deeps", 10, "A", true, "Ironforge, Forlorn Cave - Gerrig Bonegrip (50, 5)" },
        { 1275, "Researching the Corruption", 18, "A", true, "Darkshore, Auberdine- Gershala Nightwhisper (38, 43)" },
        { 1199, "Twilight Falls", 20, "A", true, "Darnassas, Craftsman's Terrace - Argent Guard Manados (55, 24)" },
        { 1198, "In Search of Thaelrid", 18, "A", true, "Darnassas, Craftsman's Terrace - Dawnwatcher Shaedlass Prerequisite to Blackfathom Villainy (55, 24)" },
        { 1200, "Blackfathom Villainy", 18, "A", "pre", "Blackfathom Deeps, Alcove SW of Ghamoo-ra - Argent Guard Thaelrid Requires In Search of Thaelrid" },
        { 1740, "The Orb of Soran'ruk", 20, "B", true, "[icon name=class_warlock]Warlock Only[/icon] The Barrens, Near Camp Taurajo - Doan Karhan /49 57" },
        { 1654, "The Test of Righteousness", 20, "A", "pre", "[icon name=class_paladin]Paladin Only[/icon] - Ironforge, inside Gates - Jordan Stilwell Starts with Tome of Valor quest chains; starts in different places depending on race. See Paladin Quest guide below. (52, 36)" },
    } },
    { name = "The Stockade", map = 34, quests = {
        { 387, "Quell The Uprising", 22, "A", true, "Stormwind, Outside Stockades - Warden Thelwater (41, 58)" },
        { 388, "The Color of Blood", 22, "A", true, "Stockades, Old Town - Nikova Raskol (patrols)" },
        { 377, "Crime and Punishment", 22, "A", true, "Duskwood, Darkshire - Councilman Millstipe (42, 47)" },
        { 386, "What Comes Around...", 22, "A", true, "Redridge Mountains, Lakeshire - Guard Berton (26, 46)" },
        { 378, "The Fury Runs Deep", 25, "A", "pre", "Wetlands, Dun Modr- Motley Garmason Requires The Dark Iron War (49, 18)" },
        { 391, "The Stockade Riots", 16, "A", "pre", "Stormwind, Outside Stockades - Warden Thelwater Requires quest line starting with The Unsent Letter from Deadmines (41, 58)" },
    } },
    { name = "Gnomeregan", map = 90, quests = {
        { 2841, "Rig Wars", 25, "H", true, "Orgrimmar, Valley of Honor - Nogg (76, 25)" },
        { 2842, "Chief Engineer Scooty", 20, "H", "pre", "Orgrimmar, Valley of Honor - Sovik Must pick up Rig Wars first. (76, 25)" },
        { 2843, "Gnomer-gooooone!", 20, "H", false, "Strangethorn Vale, Booty Bay - Scooty (27, 77)" },
        { 2922, "Save Techbot's Brain!", 20, "A", true, "Ironforge, Tinkertown - Tinkmaster Overspark (69, 50)" },
        { 2928, "Gyrodrillmatic Excavationators", 20, "A", true, "Stormwind, Dwarven Quarter- Shoni the Shilent (55, 12)" },
        { 2924, "Essential Artificials", 24, "A", true, "Ironforge, Tinkertown - Klockmort Spannerspan (47, 64)" },
        { 2930, "Data Rescue", 25, "A", true, "Ironforge, Tinkertown - Master Mechanic Castpipe (69, 48)" },
        { 2929, "The Grand Betrayal", 25, "A", true, "Ironforge, Tinkertown - High Tinker Mekkatorque (68, 49)" },
        { 2926, "Gnogaine", 20, "A", false, "Dun Morogh, Kharanos - Ozzie Togglevolt (45, 49)" },
        { 2962, "The Only Cure is More Green Glow", 20, "A", "pre", "Dun Morogh, Kharanos - Ozzie Togglevolt Complete Gnogaine first. (45, 49)" },
        { 2951, "The Sparklematic 5200!", 25, "B", true, "Gnomeregan, [object=142487], needs Grime-Encrusted Object" },
        { 2904, "A Fine Mess", 20, "B", false, "Gnomeregan Escort Kernobee from room to the right of Clean Room" },
        { 2945, "Grime-Encrusted Ring", 28, "B", true, "Gnomeregan, Grime-Encrusted Ring drop. Starts Return of the Ring / Return of the Ring" },
    } },
    { name = "Razorfen Kraul", map = 47, quests = {
        { 1102, "A Vengeful Fate", 29, "H", true, "Thunder Bluff, Near Main Lift - Auld Stonespire (37, 29)" },
        { 1109, "Going, Going, Guano!", 30, "H", true, "Undercity, The Apothecarium - Master Apothecary Faranell Prerequisite for Scarlet Monastery quest Hearts of Zeal (48, 69)" },
        { 6522, "An Unholy Alliance", 28, "H", false, "Razorfen Kraul, Small Scroll, drops from Charlga Razorflank Prerequisite for Razorfen Downs quest An Unholy Alliance" },
        { 1101, "The Crone of the Kraul", 29, "A", "pre", "Feralas, The Lower Wilds - Falfindel Waywarder Complete Lonebrow's Journal first. (89, 46)" },
        { 1142, "Mortality Wanes", 25, "A", true, "Razorfen Kraul - Heralath Fallowbrook inside instance behind main boss" },
        { 1221, "Blueleaf Tubers", 20, "B", false, "The Barrens, Ratchet - Mebok Mizzyrix Don't forget quest items next to Mizzyrix. (62, 37)" },
        { 1144, "Willix the Importer", 22, "B", false, "Razorfen Kraul, Tent near final boss - Willix the Importer" },
    } },
    { name = "Scarlet Monastery", map = 189, quests = {
        { 1048, "Into The Scarlet Monastery", 33, "H", true, "Undercity, Royal Quarter - Varimathras (56, 92)" },
        { 1053, "In the Name of the Light", 34, "A", true, "Hillsbrad Foothills, Southshore - Raleigh the Devout 3 prerequisite quests, starting with Brother Anton (51, 58)" },
        { 1051, "Vorrel's Revenge", 25, "H", true, "Scarlet Monastery, Graveyard - Vorrel Sengutz" },
        { 1113, "Hearts of Zeal", 30, "H", true, "Undercity, The Apothecarium - Master Apothecary Faranell Complete Going, Going, Guano!, Razorfen Kraul (48, 69)" },
        { 1049, "Compendium of the Fallen", 28, "H", true, "Thunder Bluff, First Rise - Sage Truthseeker Undead cannot pick up this quest (36, 26)" },
        { 1160, "Test of Lore", 25, "H", "pre", "Undercity, The Apothecarium - Parqual Fintallas Complete 6 quests in chain, starting with Test of Faith (57, 65)" },
        { 1050, "Mythology of the Titans", 28, "A", true, "Ironforge, Hall of Explorers - Librarian Mae Paledust (75, 12)" },
        { 1951, "Rituals of Power", 30, "B", "pre", "Mage Only Thousand Needles , Shimmering Flats Raceway - Magus Tirth Complete 3 quests, starting with Journey to the Marsh (78, 75)" },
    } },
    { name = "Razorfen Downs", map = 129, quests = {
        { 3341, "Bring the End", 37, "H", true, "Undercity, Magic Quarter - Andrew Brownell (74, 33)" },
        { 6521, "An Unholy Alliance", 28, "H", "pre", "Undercity, Royal Quarter - Varimathras Complete An Unholy Alliance from RFK (36, 26)" },
        { 3636, "Bring the Light", 39, "A", false, "Stormwind, Cathedral - Archbishop Benedictus (39, 27)" },
        { 6626, "A Host of Evil", 28, "B", true, "The Barrens, Outside instance portal to RFD - Myriam Moonsinger (49, 95)" },
        { 3523, "Scourge of the Downs", 32, "B", false, "Razorfen Downs, Murder Pens - Belnistrasz Entire party should complete before picking up next quest" },
        { 3525, "Extinguishing the Idol", 32, "B", false, "Razorfen Downs, Murder Pens - Belnistrasz Make sure entire party has finished Scourge of the Downs first or they won't get credit!" },
    } },
    { name = "Uldaman", map = 70, quests = {
        { 2342, "Reclaimed Treasures", 33, "H", true, "Undercity, Center - Patrick Garrett (62, 48)" },
        { 2202, "Uldaman Reagent Run", 36, "H", "pre", "Badlands, Kargath - Jarkal Mossmeld Complete Badlands Reagent Run first (3, 46)" },
        { 2283, "Necklace Recovery", 37, "H", false, "Badlands, Outside Uldaman instance - Shattered Necklace drop from Shadowforge or Shadowvault mobs" },
        { 1360, "Reclaimed Treasures", 33, "A", true, "Ironforge, Hall of Explorers - Krom Stoutarm (74, 9)" },
        { 2398, "The Lost Dwarves", 35, "A", true, "Ironforge, Hall of Explorers - Prospector Stormpike (75, 12)" },
        { 2240, "The Hidden Chamber", 35, "A", "pre", "Uldaman, Lost Dwarves area - [object=123463] Complete The Lost Dwarves first" },
        { 17, "Uldaman Reagent Run", 38, "A", "pre", "Loch Modan, Thelsamar - Ghak Healtouch Complete Badlands Reagent Run first (37, 49)" },
        { 704, "Agmond's Fate", 33, "A", "pre", "Loch Modan, Ironband's Excavation Site - Prospector Ironband Complete 3 quests, starting with Ironband Wants You! first (65, 65)" },
        { 1139, "The Lost Tablets of Will", 30, "A", "pre", "Ironforge, Hall of Explorers - Advisor Belgrum Complete 8 quests, starting with A Sign of Hope first (77, 9)" },
        { 2198, "The Shattered Necklace", 37, "A", false, "Badlands, Outside Uldaman instance - Shattered Necklace drop from Shadowforge or Shadowvault mobs" },
        { 2418, "Power Stones", 30, "B", true, "Badlands, Central - Rigglefuzz (42, 52)" },
        { 709, "Solution to Doom", 30, "B", true, "Badlands, Southern - Theldurin the Lost (51, 76)" },
        { 2278, "The Platinum Discs", 40, "B", false, "Uldaman, room after Archaedas - [object=object=131474]" },
        { 1956, "Power in Uldaman", 35, "B", "pre", "Mage Only - Dustwallow Marsh, N. of Stonemaul Ruins - Tabetha Complete 3 quests, starting with Return to the Marsh first (46, 57)" },
    } },
    { name = "Zul'Farrak", map = 209, quests = {
        { 2936, "The Spider God", 40, "H", "pre", "Durotar, Sen'jin Village - Master Gadrin Complete 3 quests first, starting with Venom Bottles (56, 74)" },
        { 2991, "Nekrum's Medallion", 40, "A", "pre", "Blasted Lands, Nethergarde Keep - Thadius Grimshade Complete 3 quests first, starting with Witherbark Cages (66, 19)" },
        { 2768, "Divino-matic Rod", 40, "B", true, "Tanaris, Gadgetzan - Chief Engineer Bilgewhizzle (52, 28)" },
        { 2865, "Scarab Shells", 40, "B", true, "Tanaris, Gadgetzan - Tran'rek (51, 26)" },
        { 3042, "Troll Temper", 40, "B", true, "Tanaris, Gadgetzan - Trenton Lighthammer (51, 28)" },
        { 2846, "Tiara of the Deep", 40, "B", true, "Dustwallow Marsh, N. of Stonemaul Ruins - Tabetha (46, 57)" },
        { 2770, "Gahz'rilla", 40, "B", true, "Thousand Needles, Shimmering Flats - Wizzle Brassbolts One group member must have Mallet of Zul'Farrak to summon Gahz'rilla - drop from Qiaga the Keeper in The Hinterlands (78, 77)" },
        { 3527, "The Prophecy of Mosh'aru", 40, "B", "pre", "Tanaris, Steamwheedle Port - Yeh'kinya Complete Screecher Spirits first (67, 22)" },
    } },
    { name = "Maraudon", map = 349, quests = {
        { 7068, "Shadowshard Fragments", 39, "H", false, "Orgrimmar, Valley of Spirits - Uthel'nay (39, 86)" },
        { 7029, "Vyletongue Corruption", 41, "H", true, "Desolace, Shadowprey Village - Vark Battlescar (23, 70)" },
        { 7064, "Corruption of Earth and Seed", 45, "H", true, "Desolace, S. of Shadowprey Village - Selendra (26, 77)" },
        { 7070, "Shadowshard Fragments", 39, "A", true, "Dustwallow Marsh, Theramore - Archmage Tervosh (66, 49)" },
        { 7041, "Vyletongue Corruption", 41, "A", true, "Desolace, Nijel's Point - Talendria (68, 8)" },
        { 7065, "Corruption of Earth and Seed", 45, "A", true, "Desolace, Nijel's Point - Keeper Marandis (63, 10)" },
        { 7028, "Twisted Evils", 41, "B", true, "Desolace, SE of Thunderaxe Fortress- Willow (62, 39)" },
        { 7044, "Legends of Maraudon", 41, "B", true, "Maraudon, Orange side, outside instance - Cavindra" },
        { 7066, "Seed of Life", 39, "B", false, "Maraudon, Zaetar's Spirit in middle of ring after killing Princess Theradras" },
        { 7067, "The Pariah's Instructions", 39, "B", false, "Desolace, South of Mannoroc Coven - Centaur Pariah patrols around /way 48.4, 87.0" },
        { 7046, "The Scepter of Celebras", 41, "B", "pre", "Maraudon, Purple side - Celebras the Redeemed Complete Legends of Maraudon first" },
    } },
    { name = "Sunken Temple", map = 109, quests = {
        { 1445, "The Temple of Atal'Hakkar", 38, "H", "pre", "Swamp of Sorrows, Stonard - Fel'zerul Complete 3 quests first, starting with Pool of Tears (47, 54)" },
        { 4146, "Zapper Fuel", 47, "H", "pre", "The Barrens, Ratchet - Liv Rizzlefix Complete 2 quests first, starting with Larion and Muigin (62, 38)" },
        { 4143, "Haze of Evil", 47, "A", "pre", "Feralas, Twin Colossals - Gregan Brewspewer Complete 2 quests first, starting with Muigin and Larion (45, 25)" },
        { 1475, "Into The Temple of Atal'Hakkar", 38, "A", "pre", "Stormwind, Dwarven District - Brohann Caskbelly Complete 6 quests first, starting with In Search of The Temple (64, 21)" },
        { 1446, "Jammal'an the Prophet", 38, "B", true, "Hinterlands, Spider area SW of Altar of Zul - Atal'ai Exile (33, 75)" },
        { 3373, "The Essence of Eranikus", 48, "B", false, "Sunken Temple, Essence of Eranikus drop from [npc=5709" },
        { 3446, "Into the Depths", 46, "B", "pre", "Tanaris, S. of Gadgetzan - Marvon Rivetseeker Complete 2 quests first, starting with The Sunken Temple/ The Sunken Temple (52, 45)" },
        { 3447, "Secret of the Circle", 46, "B", "pre", "Tanaris, S. of Gadgetzan - Marvon Rivetseeker Complete 2 quests first, starting with The Sunken Temple/ The Sunken Temple (52, 45)" },
        { 3528, "The God Hakkar", 40, "B", true, "Tanaris, Steamwheedle Port - Yeh'kinya Complete 3 quests first, starting with Screecher Spirits (67, 22)" },
    } },
    { name = "Blackrock Depths", map = 230, quests = {
        { 4081, "KILL ON SIGHT: Dark Iron Dwarves", 48, "H", true, "Badlands, Kargath - [object=164867] poster (4, 47)" },
        { 4134, "Lost Thunderbrew Recipe", 50, "H", true, "Badlands, Kargath - Shadowmage Vivian Lagrave Breadcrumb Vivian Lagrave in Undercity for easy XP (3, 48)" },
        { 4082, "KILL ON SIGHT: High Ranking Dark Iron Officials", 50, "H", "pre", "Badlands, Kargath - [object=164867] poster Complete KILL ON SIGHT: Dark Iron Dwarves first (4, 47)" },
        { 4063, "The Rise of the Machines", 52, "H", "pre", "Badlands, Eastern - Lotwil Veriatus Complete 2 quests first, starting with The Rise of the Machines (25, 44)" },
        { 3906, "Disharmony of Flame", 48, "H", true, "Badlands, Kargath - Thunderheart (3.6, 48)" },
        { 3907, "Disharmony of Fire", 48, "H", "pre", "Badlands, Kargath - Thunderheart Opens after completing Disharmony of Flame (3.6, 48)" },
        { 3981, "Commander Gor'shak", 48, "H", "pre", "Badlands, Kargath - Galamav the Marksman Opens after completing Disharmony of Flame (6, 47)" },
        { 7201, "The Last Element", 48, "H", "pre", "Badlands, Kargath - Shadowmage Vivian Lagrave Opens after completing Disharmony of Flame (3, 48)" },
        { 4132, "Operation: Death to Angerforge", 52, "H", true, "Badlands, Kargath - Warlord Goretooth Complete 3 quests first, starting with KILL ON SIGHT: Dark Iron Dwarves. This includes Grark Lorkrub, a long escort quest. (6, 47)" },
        { 4003, "The Royal Rescue", 48, "H", true, "Orgrimmar, Valley of Wisdom - Thrall Complete 4 quests first, starting with Commander Gor'shak (32, 38)" },
        { 4262, "Overmaster Pyron", 48, "A", true, "Burning Steppes, Morgan's Vigil - Jalinda Sprig (85, 70)" },
        { 4263, "Incendius!", 48, "A", true, "Burning Steppes, Morgan's Vigil - Jalinda Sprig Complete Overmaster Pyron first (85, 70)" },
        { 4286, "The Good Stuff", 50, "A", true, "Burning Steppes, Morgan's Vigil - Oralius (84, 68)" },
        { 4126, "Hurley Blackbreath", 50, "A", true, "Dun Morogh, Kharanos - Ragnar Thunderbrew (46, 52)" },
        { 4341, "Kharan Mighthammer", 50, "A", "pre", "Ironforge, Throne Room - King Magni Bronzebeard Complete 2 quests first, starting with The Smoldering Ruins of Thaurissan (39, 56)" },
        { 4362, "The Fate of the Kingdom", 50, "A", "pre", "Ironforge, Throne Room - King Magni Bronzebeard Complete 2 quests first, starting with Kharan Mighthammer (39, 56)" },
        { 4241, "Marshal Windsor", 48, "A", "pre", "Burning Steppes, Morgan's Vigil- Marshal Maxwell Complete 2 quests first, starting with Dragonkin Menace (84, 68)" },
        { 4322, "Jail Break!", 50, "A", "pre", "Blackrock Depths , Prison Cell - Marshal Windsor Complete 6 quests first, starting with Dragonkin Menace and moving through Marshal Windsor until A Shred of Hope" },
        { 4136, "Ribbly Screwspigot", 50, "B", true, "Burning Steppes, Flame Crest - Yuka Screwspigot Can pick up breadcrumb Yuka Screwspigot in Steamwheedle Port for easy XP (66, 21)" },
        { 4123, "The Heart of the Mountain", 50, "B", true, "Burning Steppes, Flame Crest - Maxwort Uberglint (65, 23)" },
        { 7848, "Attunement to the Core", 55, "B", false, "Blackrock Mountain, Lothos Riftwaker" },
        { 3802, "Dark Iron Legacy", 48, "B", "pre", "Blackrock Mountain, Structure in middle - Franclorn Forgewright NPC is only visible if you are dead Complete Dark Iron Legacy first" },
        { 4201, "The Love Potion", 50, "B", false, "Blackrock Depths, Grim Guzzler - Mistress Nagmara" },
        { 4024, "A Taste of Flame", 52, "B", true, "Burning Steppes, Cave in NE - Cyrus Therepentous Complete 11 quests first, starting with Divine Retribution (95, 31)" },
    } },
    { name = "Dire Maul", map = 429, quests = {
        { 7489, "Lethtendris's Web", 54, "H", true, "Feralas, Camp Mojache - Talo Thornhoof (76, 43)" },
        { 7488, "Lethtendris's Web", 54, "A", true, "Feralas, Feathermoon Stronghold - Latronicus Moonspear (30, 46)" },
        { 7441, "Pusillin and the Elder Azj'Tordin", 54, "B", true, "Feralas, Lariss Pavillion - Azj'Tordin (76, 37)" },
        { 5526, "Shards of the Felvine", 56, "B", "pre", "Moonglade, Nighthaven - Rabine Saturna Complete A Reliquary of Purity from same NPC and explore all of Dire Maul first to open quest (51, 45)" },
        { 7463, "Arcane Refreshment", 60, "B", true, "Mage Only - Dire Maul, Library - Lorekeeper Lydros" },
        { 7461, "The Madness Within", 56, "B", true, "Dire Maul, West, second floor - Shen'dralar Ancient" },
        { 7507, "Foror's Compendium", 60, "B", false, "Dire Maul - Nostro's Compendium of Dragon Slaying, rare drop or looted from [object=179547]. Not BoP. Used to create BoP tanking sword ." },
        { 7481, "Elven Legends", 54, "H", true, "Feralas, Camp Mojache - Sage Korolusk Complete to be eligible for Libram of Protection, Libram of Rapidity, and Libram of Focus (74, 43)" },
        { 7482, "Elven Legends", 54, "A", true, "Feralas, Feathermoon Stronghold - Scholar Runethorn Complete to be eligible for Libram of Protection, Libram of Rapidity, and Libram of Focus (31, 43)" },
        { 5525, "Free Knot!", 56, "B", true, "Dire Maul, North - Knot Thimblejack Cannot be completed during Tribute Run unless a party member already has Gordok Shackle Key" },
        { 5518, "The Gordok Ogre Suit", 56, "B", true, "Dire Maul, North - Knot Thimblejack" },
        { 5528, "The Gordok Taste Test", 56, "B", true, "Dire Maul, North - Stomper Kreeg Can only be picked up after completing a Tribute Run" },
        { 7703, "Unfinished Gordok Business", 56, "B", true, "Dire Maul, North - Captain Kromcrush Requires completing one Tribute Run first, and a second Tribute Run after killing Prince Tortheldrin and looting the Gauntlet of Gordok Might" },
    } },
    { name = "Lower Blackrock Spire", map = 229, quests = {
        { 4724, "The Pack Mistress", 55, "H", true, "Badlands, Kargath- Galamav the Marksman (6, 47)" },
        { 4981, "Operative Bijou", 55, "H", true, "Badlands, Kargath - Lexlort Leads to Bijou's Belongings inside LBRS (5, 47)" },
        { 4903, "Warlord's Command", 55, "H", false, "Badlands, Kargath - Warlord Goretooth (5, 47)" },
        { 4701, "Put Her Down", 55, "A", true, "Burning Steppes, Morgan's Vigil - Helendis Riverhorn (65, 69)" },
        { 5089, "General Drakkisath's Command", 55, "A", false, "Blackrock Spire, Lower, General Drakkisath's Command, dropped from Overlord Wyrmthalak" },
        { 5001, "Bijou's Belongings", 55, "A", true, "Blackrock Spire, Lower - Bijou" },
        { 4862, "En-Ay-Es-Tee-Why", 55, "B", true, "Burning Steppes, Flame Crest - Kibler (65, 21)" },
        { 4729, "Kibler's Exotic Pets", 55, "B", false, "Burning Steppes, Flame Crest - Kibler (65, 21)" },
        { 4866, "Mother's Milk", 55, "B", true, "Burning Steppes, Flame Crest - Ragged John (65, 23)" },
        { 4742, "Seal of Ascension", 57, "B", false, "Blackrock Spire, Lower - Unadorned Seal of Ascension, Gemstone of Smolderthorn, Gemstone of Spirestone, Gemstone of Bloodaxe" },
        { 4867, "Urok Doomhowl", 55, "B", false, "Blackrock Spire, Lower, Warosh, patrols near beginning of instance" },
        { 4788, "The Final Tablets", 40, "B", "pre", "Tanaris, Steamsheedle Port- Prospector Ironboot Complete 5 quests first, starting with Screecher Spirits (66, 24)" },
    } },
    { name = "Scholomance", map = 289, quests = {
        { 5341, "Barov Family Fortune", 52, "H", true, "Tirisfal Glades, The Bulwark - Alexi Barov Alexi Barov may be dead due to Alliance kill quest; 30m spawn timer (83, 71)" },
        { 7668, "The Darkreaver Menace", 58, "H", "pre", "Shaman Only - Orgrimmar, Valley of Wisdom - Sagorne Creststrider Complete Material Assistance first (38, 35)" },
        { 5343, "Barov Family Fortune", 52, "A", true, "Western Plaguelands, Chillwind Camp - Weldon Barov Weldon Barov may be dead due to Horde kill quest; 30m spawn timer (43, 83)" },
        { 5529, "Plagued Hatchlings", 55, "B", true, "Eastern Plaguelands, Light's Hope Chapel - Betina Bigglezink (81, 59)" },
        { 5582, "Healthy Dragon Scale", 55, "B", "pre", "Scholomance, Healthy Dragon Scale, drops from Plagued Hatchlings Complete Plagued Hatchlings first - repeatable for Argent Dawn rep" },
        { 5382, "Doctor Theolen Krastinov, the Butcher", 55, "B", true, "Western Plaguelands, Caer Darrow - Eva Sarkhoff (70, 73)" },
        { 5515, "Krastinov's Bag of Horrors", 55, "B", "pre", "Western Plaguelands, Caer Darrow - Eva Sarkhoff Complete Doctor Theolen Krastinov, the Butcher first (70, 73)" },
        { 5384, "Kirtonos the Herald", 55, "B", true, "Western Plaguelands, Caer Darrow - Eva Sarkhoff Complete Krastinov's Bag of Horrors first; save reward item (70, 73)" },
        { 4771, "Dawn's Gambit", 57, "B", "pre", "Eastern Plaguelands, Light's Hope Chapel - Betina Bigglezink Complete 9 quests, starting with Broodling Essence first (81, 59)" },
        { 5466, "The Lich, Ras Frostwhisper", 57, "B", "pre", "Western Plaguelands, Caer Darrow - Magistrate Marduke Complete 8 quests, starting with Doctor Theolen Krastinov, the Butcher first Must have equipped to see Magistrate Marduke (70, 74)" },
    } },
    { name = "Stratholme", map = 329, quests = {
        { 5214, "The Great Ezra Grimm", 55, "B", true, "Eastern Plaguelands, Light's Hope Chapel - Smokey LaRue (80, 58)" },
        { 5251, "The Archivist", 55, "B", true, "Eastern Plaguelands, Light's Hope Chapel - Duke Nicholas Zverenhoff (81, 59)" },
        { 5282, "The Restless Souls", 55, "B", "pre", "Eastern Plaguelands, Terrordale - Egan (14, 33)" },
        { 5122, "The Medallion of Faith", 55, "B", true, "Stratholme, Undead Side - Aurius inside chapel at beginning Complete quest to pick up The Restless Souls on Undead side" },
        { 5262, "The Truth Comes Crashing Down", 55, "B", "pre", "Stratholme, Live - Head of Balnazzar from Balnazzar Complete The Archivist to be eligible for drop" },
        { 5848, "Of Love and Family", 52, "B", "pre", "Western Plaguelands, Caer Darrow - Artist Renfray Complete 7 quests, starting with Blood Tinged Skies, Carrion Grubbage, and Demon Dogs (65, 75)" },
        { 6163, "Ramstein", 56, "H", "pre", "Eastern Plaguelands, Marris Stead - Nathanos Blightcaller Complete 4 quests, starting with The Ranger Lord's Behest and To Kill With Purpose (26, 74)" },
        { 5243, "Houses of the Holy", 55, "B", true, "Eastern Plaguelands, Light's Hope Chapel - Leonid Barthalomew the Revered (81, 57)" },
        { 5212, "The Flesh Does Not Lie", 55, "B", "pre", "Eastern Plaguelands, Light's Hope Chapel - Betina Bigglezink (81, 59)" },
        { 5213, "The Active Agent", 55, "B", true, "Eastern Plaguelands, Light's Hope Chapel - Betina Bigglezink Complete The Flesh Does Not Lie first (81, 59)" },
        { 5125, "Aurius' Reckoning", 55, "B", "pre", "Stratholme, Undead Side - Aurius in chapel at beginning Complete The Medallion of Faith first" },
        { 5263, "Above and Beyond", 55, "B", "pre", "Eastern Plaguelands, Light's Hope Chapel - Duke Nicholas Zverenhoff Complete 2 quests staring with The Archivist (81, 59)" },
        { 5463, "Menethil's Gift", 57, "B", "pre", "Eastern Plaguelands, Light's Hope Chapel - Leonid Barthalomew the Revered Complete 5 quests, starting with Doctor Theolen Krastinov, the Butcher first (81, 57)" },
        { 8945, "Dead Man's Plea", 58, "B", "pre", "Eastern Plaguelands, Stratholme Main Entrance - Anthion Harmon Complete 9 quests, starting with A Supernatural Device / A Supernatural Device. Requires Extra-Dimensional Ghost Revealer to see quest NPC (30, 16)" },
    } },
    { name = "Upper Blackrock Spire", map = 229, quests = {
        { 4768, "The Darkstone Tablet", 57, "H", true, "Badlands, Kargath - Shadowmage Vivian Lagrave Pick up non-required breadcrumb Vivian Lagrave and the Darkstone Tablet in Undercity for easy XP (3, 48)" },
        { 4974, "For The Horde!", 55, "H", "pre", "Orgrimmar, Valley of Wisdom - Thrall Complete 2 quests, starting with Warlord's Command first (31, 37)" },
        { 6602, "Blood of the Black Dragon Champion", 55, "H", "pre", "Desolace, Rexxar, patrols (see database for path) Complete 13 quests, starting with Warlord's Command first" },
        { 4764, "Doomrigger's Clasp", 57, "A", true, "Burning Steppes, Morgan's Vigil - Mayara Brightwing Pick up non-required breadcrumb Mayara Brightwing in Stormwind Keep for easy XP (84, 69)" },
        { 5102, "General Drakkisath's Demise", 55, "A", "pre", "Burning Steppes, Morgan's Vigil - Marshal Maxwell Complete General Drakkisath's Command first (84, 68)" },
        { 6502, "Drakefire Amulet", 50, "A", "pre", "Winterspring, Mazthoril- Haleh Step on blue rune at end of cave to spawn NPC Complete 10 quests, starting with Dragonkin Menace (56, 49)" },
        { 7761, "Blackhand's Command", 55, "B", false, "Blackrock Mountain, Side hallway on way to BWL - Blackhand's Command dropped by Scarshield Quartermaster" },
        { 5160, "The Matron Protectorate", 57, "B", false, "Blackrock Spire, Upper, Awbee, on small ledge in room after killing Blackhand" },
        { 5047, "Finkle Einhorn, At Your Service!", 57, "B", false, "Blackrock Spire, Upper- Pip Quickwit, only spawns after Skinner (300) skins The Beast with Pip Quickwit" },
        { 4735, "Egg Collection", 57, "B", "pre", "Burning Steppes, Flame Crest - Tinkee Steamboil Complete 6 quests, starting with Egg Freezing and Broodling Essence from same NPC (65, 23)" },
        { 6821, "Eye of the Emberseer", 55, "B", "pre", "Azshara - Duke Hydraxis Complete 2 quests, Stormers and Rumblers and Poisoned Water from same NPC (79, 73)" },
        { 5127, "The Demon Forge", 55, "B", "pre", "[icon name=trade_blacksmithing]Blacksmiths Only[/icon] - Winterspring, Southeast - Lorax Complete Lorax's Tale from same NPC. Rewards Plans: Demon Forged Breastplate (63, 73)" },
    } },
}
