-------------------------------------------------------------------------------
--  NaowhForever_BadgesPatrons.lua -- GENERATED by the daily badge sync from naowh.gg: the
--  active Legendary patrons, by region and character GUID, with the month their pledge
--  started. Do not edit by hand; the next sync overwrites it.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.BADGE_PATRONS = {
}
