"""Build NaowhForever_DungeonQuestChains.lua from Wowhead's Forever quest pages.

Each quest page (/forever/quest=<id>) with a chain has a "Series" box in its infobox: a
<table class="series"> with one row per step in order, each step a link to its quest, or
<b> for the page's own quest. A row can hold more than one quest (the faction or class
versions of that step). Every quest ID in NaowhForever_DungeonQuestData.lua is looked up,
including its alt, steps and lead IDs. Answers are cached in quest_chains.json (null for
a quest with no chain); delete an entry to fetch it again.

Usage: python Tools/build_quest_chains.py
"""
import html
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "DungeonQuests" / "NaowhForever_DungeonQuestData.lua"
OUT = ROOT / "DungeonQuests" / "NaowhForever_DungeonQuestChains.lua"
CACHE = Path(__file__).resolve().parent / "quest_chains.json"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    # Wowhead's CDN answers 403 once requests come too fast; it lifts after a pause.
    for wait in (30, 60, 120, 240, None):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read().decode("utf-8")
        except urllib.error.HTTPError as e:
            if e.code not in (403, 429, 503) or wait is None:
                raise
            print(f"  {e.code} from {urllib.parse.urlsplit(url).netloc}, retrying in {wait}s", file=sys.stderr)
            time.sleep(wait)


def quest_ids():
    """Every quest ID in the data file, its own first, in file order."""
    ids = []
    src = DATA.read_text(encoding="utf-8")
    for line in re.findall(r'^\s+\{ \d+, ".*$|^\s+steps = .*$', src, re.M):
        own = re.match(r'\s+\{ (\d+), "', line)
        found = [own.group(1)] if own else []
        for field in re.findall(r'(?:alt|steps|lead) = (\{(?:[^{}]|\{[^{}]*\})*\})', line):
            found += re.findall(r"\d+", field)
        for i in found:
            if int(i) not in ids:
                ids.append(int(i))
    return ids


def parse(quest_id, page):
    """{ "chain": [[ids of step 1], ...], "names": { id: name } }, or None without a chain."""
    table = re.search(r'<table class="series">(.*?)</table>', page, re.S)
    if not table:
        return None
    chain, names = [], {}
    for row in re.findall(r"<tr>(.*?)</tr>", table.group(1), re.S):
        step = []
        for qid, name in re.findall(r'href="/forever/quest=(\d+)[^"]*">([^<]*)</a>', row):
            step.append(int(qid))
            names[qid] = html.unescape(name)
        own = re.search(r"<b>([^<]*)</b>", row)
        if own:
            step.insert(0, quest_id)
            names[str(quest_id)] = html.unescape(own.group(1))
        if not step:
            raise ValueError(f"quest {quest_id}: series row without a quest: {row!r}")
        chain.append(step)
    return {"chain": chain, "names": names}


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    cache = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.exists() else {}
    ids = quest_ids()
    failed = []
    for quest_id in ids:
        key = str(quest_id)
        if key in cache:
            continue
        try:
            cache[key] = parse(quest_id, fetch(f"https://www.wowhead.com/forever/quest={quest_id}"))
        except (urllib.error.HTTPError, ValueError) as e:
            failed.append(f"{quest_id}: {e}")
            continue
        CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True), encoding="utf-8")
        time.sleep(1)

    own = set(int(i) for i in re.findall(r'^\s+\{ (\d+), "', DATA.read_text(encoding="utf-8"), re.M))
    chains, names = {}, {}
    for quest_id in ids:
        entry = cache.get(str(quest_id))
        if not entry or len(entry["chain"]) < 2:
            continue
        chains[quest_id] = entry["chain"]
        for step in entry["chain"]:
            for i in step:
                if i not in own:
                    names[i] = entry["names"][str(i)]

    def step_lua(step):
        return str(step[0]) if len(step) == 1 else "{ " + ", ".join(str(i) for i in step) + " }"

    lines = [
        "-------------------------------------------------------------------------------",
        "--  NaowhForever_DungeonQuestChains.lua -- the quest chain each dungeon quest belongs to,",
        "--  from the Series box on Wowhead's Forever quest pages. Generated by",
        "--  Tools/build_quest_chains.py; do not edit by hand.",
        "--",
        "--  DungeonQuestChains: questID -> every step of its chain in order, itself included. A",
        "--  step is a quest ID, or a table of IDs (one per faction or class), any of which counts.",
        "--  DungeonQuestChainNames: the names of the steps that are not quests in the data file.",
        "-------------------------------------------------------------------------------",
        "local ns = _G.NaowhForever",
        "",
        "ns.DungeonQuestChains = {",
    ]
    for quest_id in sorted(chains):
        lines.append(f"    [{quest_id}] = {{ {', '.join(step_lua(s) for s in chains[quest_id])} }},")
    lines.append("}")
    lines.append("")
    lines.append("ns.DungeonQuestChainNames = {")
    for quest_id in sorted(names):
        lines.append(f"    [{quest_id}] = {lua_string(names[quest_id])},")
    lines.append("}")
    OUT.write_text("\r\n".join(lines) + "\r\n", encoding="utf-8", newline="")

    print(f"{len(ids)} quests, {len(chains)} in a chain, {len(names)} step names -> {OUT.name}", file=sys.stderr)
    if failed:
        print(f"{len(failed)} could not be read; run again to retry:", file=sys.stderr)
        for line in failed:
            print(f"  {line}", file=sys.stderr)


if __name__ == "__main__":
    main()
