-------------------------------------------------------------------------------
--  Data/Build.lua -- the WoW Forever build the Dungeon Journal's game data is read from,
--  and the day it came out (the day wago.tools listed it), shown by the window's title.
--  Generated by Tools/build_factions.py, and moved on by the daily build watcher; do not edit.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.DATA_BUILD = "1.60.1.70170"
ns.Journal.DATA_DATE = "1 Oct 2026"
