-------------------------------------------------------------------------------
--  Data/Dungeons/BlackrockDepths.lua -- Blackrock Depths in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackrockDepths", {
    name = "Blackrock Depths",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 27.6, y = 72.4 },
    wings = {
        { name = "Detention Block", bosses = {
            { npc = 9018, name = "High Interrogator Gerstahn", encounters = { 227 }, loot = { 22240 }, chance = { 13 } },
            { npc = 9025, name = "Lord Roccor", encounters = { 228 }, loot = { 11632, 11631 }, chance = { 28, 28 } },
            { npc = 9319, name = "Houndmaster Grebmar", encounters = { 229 }, loot = { 11627, 11623, 11628 }, chance = { 37, 20, 10 } },
        } },
        { name = "Ring of Law", bosses = {
            { npc = 9031, name = "Anub'shiah", loot = { 11731 }, chance = { 9 } },
            { npc = 9029, name = "Eviscerator", loot = { 11730 }, chance = { 13 } },
            { npc = 9027, name = "Gorosh the Dervish", loot = { 11726 }, chance = { 12 } },
            { npc = 9028, name = "Grizzle" },
            { npc = 9032, name = "Hedrum the Creeper", loot = { 11633, 11729 }, chance = { 33, 11 } },
            { npc = 9030, name = "Ok'thor the Breaker", loot = { 11728 }, chance = { 12 } },
        } },
        { name = "Shadowforge City", bosses = {
            { npc = 9024, name = "Pyromancer Loregrain", encounters = { 231 }, loot = { 11748, 11747, 11749, 11750 }, chance = { 28, 24, 24, 20 } },
            { npc = 9017, name = "Lord Incendius", encounters = { 232 }, loot = { 11764, 11765 }, chance = { 14, 13 } },
            { npc = 9041, name = "Warder Stilgiss", encounters = { 233 }, loot = { 22241 }, chance = { 19 } },
            { npc = 9042, name = "Verek", loot = { 22242 }, chance = { 9 } },
            { npc = 9056, name = "Fineous Darkvire", encounters = { 234 }, loot = { 11841 }, chance = { 27 } },
            { npc = 9016, name = "Bael'Gar", encounters = { 235 } },
            { npc = 9033, name = "General Angerforge", encounters = { 236 }, loot = { 11821, 11817 }, chance = { 12, 10 } },
            { npc = 8983, name = "Golem Lord Argelmach", encounters = { 237 }, loot = { 11823, 11822 }, chance = { 37, 36 } },
            { npc = 9537, name = "Hurley Blackbreath", encounters = { 238 }, loot = { 11735 }, chance = { 10 } },
            { npc = 9502, name = "Phalanx", encounters = { 239 }, loot = { 11745, 11746 }, chance = { 29, 9 } },
            { npc = 9543, name = "Ribbly Screwspigot", encounters = { 240 } },
            { npc = 9499, name = "Plugger Spazzring", encounters = { 241 } },
            { npc = 9156, name = "Ambassador Flamelash", encounters = { 242 } },
            { npc = 9938, name = "Magmus", encounters = { 244 }, loot = { 11746 }, chance = { 21 } },
            { npc = 9019, name = "Emperor Dagran Thaurissan", encounters = { 2790 }, loot = { 16724 }, chance = { 3 } },
        } },
    },
})
