-------------------------------------------------------------------------------
--  Data/Dungeons/DireMaul.lua -- Dire Maul in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("DireMaul", {
    name = "Dire Maul",
    zone = "Feralas", territory = "Contested",
    entrance = { map = 1444, x = 61.9, y = 31.6 },
    wings = {
        { name = "East", bosses = {
            { npc = 14354, name = "Pusillin", encounters = { 2792 } },
            { npc = 11490, name = "Zevrim Thornhoof", encounters = { 343 } },
            { npc = 13280, name = "Hydrospawn", encounters = { 344 } },
            { npc = 14327, name = "Lethtendris", encounters = { 345 } },
            { npc = 11492, name = "Alzzin the Wildshaper", encounters = { 346 } },
        } },
        { name = "West", bosses = {
            { npc = 11489, name = "Tendris Warpwood", encounters = { 350 } },
            { npc = 11488, name = "Illyanna Ravenoak", encounters = { 347 } },
            { npc = 11487, name = "Magister Kalendris", encounters = { 348 } },
            { npc = 11496, name = "Immol'thar", encounters = { 349 } },
            { npc = 11486, name = "Prince Tortheldrin", encounters = { 361 } },
        } },
        { name = "North", bosses = {
            { npc = 14326, name = "Guard Mol'dar", encounters = { 362 } },
            { npc = 14322, name = "Stomper Kreeg", encounters = { 363 } },
            { npc = 14321, name = "Guard Fengus", encounters = { 364 } },
            { npc = 14323, name = "Guard Slip'kik", encounters = { 365 } },
            { npc = 14325, name = "Captain Kromcrush", encounters = { 366 } },
            { npc = 11501, name = "King Gordok", encounters = { 368 } },
        } },
    },
})
