-------------------------------------------------------------------------------
--  Data/Dungeons/DrownedCity.lua -- The Drowned City in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("DrownedCity", {
    name = "The Drowned City",
    new = true,
    zone = "Stranglethorn Vale", territory = "Contested",
    entrance = { map = 1434, x = 21.4, y = 27.9 },
    wings = {
        { bosses = {
            { npc = 270882, name = "Zul'Alai" },
            { npc = 270883, name = "Var'Taka" },
            { npc = 270884, name = "Captain Dreadrise" },
            { npc = 270885, name = "Deathless Marrow" },
            { npc = 270886, name = "Min'loth the Serpent" },
        } },
    },
})
