-------------------------------------------------------------------------------
--  Data/Dungeons/HallOfThanes.lua -- The Hall of Thanes in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("HallOfThanes", {
    name = "The Hall of Thanes",
    new = true,
    zone = "Ironforge", territory = "Alliance",
    entrance = { map = 1455, x = 43.0, y = 51.0 },
    wings = {
        { bosses = {
            { npc = 261306, name = "Faldrim Anvilmar", encounters = { 3493 }, loot = { 271097, 270227, 271096 } },
            { npc = 261316, name = "Magmatus", encounters = { 3495 }, loot = { 270230, 270231, 271095 } },
            { npc = 261311, name = "Plunder", encounters = { 3494 }, loot = { 270228, 271098, 270229 } },
            { npc = 261319, name = "Durgen Dirgehammer", encounters = { 3496 }, loot = { 270256, 270260, 270261 } },
        } },
    },
})
