-------------------------------------------------------------------------------
--  Data/Dungeons/LowerBlackrockSpire.lua -- Lower Blackrock Spire in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("LowerBlackrockSpire", {
    name = "Lower Blackrock Spire",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 41.1, y = 95.3 },
    wings = {
        { bosses = {
            { npc = 9196, name = "Highlord Omokk", encounters = { 267 }, loot = { 16670 }, chance = { 11 } },
            { npc = 9236, name = "Shadow Hunter Vosh'gajin", encounters = { 268 }, loot = { 16712, 12651 }, chance = { 18, 7 } },
            { npc = 9237, name = "War Master Voone", encounters = { 269 }, loot = { 16676 }, chance = { 18 } },
            { npc = 10596, name = "Mother Smolderweb", encounters = { 270 }, loot = { 16715 }, chance = { 16 } },
            { npc = 10584, name = "Urok Doomhowl", encounters = { 271 } },
            { npc = 9736, name = "Quartermaster Zigris", encounters = { 272 }, loot = { 16713, 16735, 16703, 16673, 16696, 16680, 16683, 16716 }, chance = { 2, 2, 2, 2, 2, 2, 2, 1 } },
            { npc = 10268, name = "Gizrul the Slavener", encounters = { 273 }, loot = { 16718 }, chance = { 18 } },
            { npc = 10220, name = "Halycon", encounters = { 274 } },
            { npc = 9568, name = "Overlord Wyrmthalak", encounters = { 275 }, loot = { 16679 }, chance = { 17 } },
        } },
    },
})
