-------------------------------------------------------------------------------
--  Data/Dungeons/Maraudon.lua -- Maraudon in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Maraudon", {
    name = "Maraudon",
    zone = "Desolace", territory = "Contested",
    entrance = { map = 1443, x = 30.1, y = 61.9 },
    wings = {
        { bosses = {
            { npc = 13282, name = "Noxxion", encounters = { 422 }, loot = { 17745 }, chance = { 18 } },
            { npc = 12258, name = "Razorlash", encounters = { 423 }, loot = { 17748 }, chance = { 24 } },
            { npc = 12236, name = "Lord Vyletongue", encounters = { 424 }, loot = { 17755 }, chance = { 28 } },
            { npc = 12225, name = "Celebras the Cursed", encounters = { 425 }, loot = { 17739, 17738, 17740 }, chance = { 32, 32, 31 } },
            { npc = 12203, name = "Landslide", encounters = { 426 }, loot = { 17943 }, chance = { 26 } },
            { npc = 13601, name = "Tinkerer Gizlock", encounters = { 427 }, loot = { 17719, 17717 }, chance = { 33, 33 } },
            { npc = 13596, name = "Rotgrip", encounters = { 428 }, loot = { 17732, 17728, 17730 }, chance = { 36, 35, 24 } },
            { npc = 12201, name = "Princess Theradras", encounters = { 429 }, loot = { 17713, 17714, 17766, 17715, 17710 }, chance = { 25, 24, 20, 19, 19 } },
            { npc = 12237, name = "Meshlok the Harvester", rare = true, loot = { 17741 }, chance = { 29 } },
        } },
    },
})
