-------------------------------------------------------------------------------
--  Data/Dungeons/RazorfenKraul.lua -- Razorfen Kraul in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("RazorfenKraul", {
    name = "Razorfen Kraul",
    zone = "The Barrens", territory = "Horde",
    entrance = { map = 1413, x = 42.2, y = 89.8 },
    wings = {
        { bosses = {
            { npc = 4424, name = "Aggem Thorncurse", encounters = { 2774 }, loot = { 6681, 1978, 2549 }, chance = { 47, 1, 1 } },
            { npc = 4428, name = "Death Speaker Jargba", encounters = { 2775 }, loot = { 6685, 6682, 2816 }, chance = { 44, 43, 10 } },
            { npc = 4420, name = "Overlord Ramtusk", encounters = { 2776 }, loot = { 6686, 6687 }, chance = { 62, 34 } },
            { npc = 4422, name = "Agathelos the Raging", encounters = { 2777 }, loot = { 6690, 6691 }, chance = { 62, 34 } },
            { npc = 4421, name = "Charlga Razorflank", encounters = { 2778 }, loot = { 6693, 6692 }, chance = { 66, 17 } },
            { npc = 4425, name = "Blind Hunter", rare = true, loot = { 6697, 6696, 6695 }, chance = { 34, 34, 26 } },
            { npc = 4842, name = "Earthcaller Halmgar", rare = true, loot = { 6688, 2264 }, chance = { 46, 12 } },
        } },
    },
})
