-------------------------------------------------------------------------------
--  Data/Dungeons/RazorfenDowns.lua -- Razorfen Downs in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("RazorfenDowns", {
    name = "Razorfen Downs",
    zone = "The Barrens", territory = "Horde",
    entrance = { map = 1413, x = 50.9, y = 92.9 },
    wings = {
        { bosses = {
            { npc = 7355, name = "Tuten'kash", encounters = { 2780 }, loot = { 10775 }, chance = { 32 } },
            { npc = 7357, name = "Mordresh Fire Eye", encounters = { 2782 }, loot = { 10771 }, chance = { 32 } },
            { npc = 8567, name = "Glutton", encounters = { 2784 }, loot = { 10772, 10774 }, chance = { 50, 48 } },
            { npc = 7358, name = "Amnennar the Coldbringer", encounters = { 2785 }, loot = { 10762, 10763, 10764, 10765, 10761 }, chance = { 39, 37, 29, 27, 19 } },
            { npc = 7354, name = "Ragglesnout", rare = true, encounters = { 2783 } },
        } },
    },
})
