-------------------------------------------------------------------------------
--  Data/Dungeons/RuinsOfLordaeron.lua -- Ruins of Lordaeron in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("RuinsOfLordaeron", {
    name = "Ruins of Lordaeron",
    new = true,
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1458, x = 71.6, y = 11.4 },
    wings = {
        { bosses = {
            { npc = 250483, name = "Witherfang", encounters = { 3353 }, loot = { 271201, 271203, 271202 } },
            { npc = 250660, name = "The Baron", encounters = { 3355 }, loot = { 271204, 271205, 271206 } },
            { npc = 256035, name = "Viktor the Vile", encounters = { 3411 }, loot = { 271218, 271212, 271211 } },
            { npc = 250631, name = "The Abandoned", encounters = { 3357 }, loot = { 271216, 271208, 271207 } },
            { npc = 256097, name = "Bjork", encounters = { 3412 }, loot = { 271217, 271209, 271210 } },
            { npc = 250657, name = "Rath'mael", encounters = { 3354 }, loot = { 271213, 271215, 271214 } },
            { npc = 255699, name = "Lordaeron Captain", rare = true, encounters = { 3408 } },
        } },
    },
})
