-------------------------------------------------------------------------------
--  Data/Dungeons/ScarletMonastery.lua -- Scarlet Monastery in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ScarletMonastery", {
    name = "Scarlet Monastery",
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1420, x = 83.9, y = 31.6 },
    wings = {
        { name = "Graveyard", bosses = {
            { npc = 3983, name = "Interrogator Vishas", encounters = { 444 }, loot = { 7683, 7682, 7727 }, chance = { 51, 6, 1 } },
            { npc = 4543, name = "Bloodmage Thalnos", encounters = { 2779 }, loot = { 7685, 7684 }, chance = { 50, 48 } },
            { npc = 6490, name = "Azshir the Sleepless", rare = true, loot = { 7731, 7708, 7709 }, chance = { 34, 32, 31 } },
            { npc = 6488, name = "Fallen Champion", rare = true, loot = { 7690, 7691, 7689 }, chance = { 40, 38, 18 } },
            { npc = 6489, name = "Ironspine", rare = true, loot = { 7686, 7688, 7687 }, chance = { 41, 35, 20 } },
        } },
        { name = "Library", bosses = {
            { npc = 3974, name = "Houndmaster Loksey", encounters = { 446 }, loot = { 7710 }, chance = { 14 } },
            { npc = 6487, name = "Arcanist Doan", encounters = { 447 }, loot = { 7714, 7713, 7711 }, chance = { 47, 47, 46 } },
        } },
        { name = "Armory", bosses = {
            { npc = 3975, name = "Herod", encounters = { 448 }, loot = { 7719, 10330, 7717 }, chance = { 33, 14, 14 } },
        } },
        { name = "Cathedral", bosses = {
            { npc = 4542, name = "High Inquisitor Fairbanks", encounters = { 449 }, loot = { 19507, 19508, 19509 }, chance = { 34, 32, 32 } },
            { npc = 3976, name = "Scarlet Commander Mograine", loot = { 7726, 7724, 7723, 10330 }, chance = { 43, 20, 19, 14 } },
            { npc = 3977, name = "High Inquisitor Whitemane", encounters = { 450 }, loot = { 7721 }, chance = { 19 } },
        } },
    },
})
