-------------------------------------------------------------------------------
--  Data/Dungeons/Scholomance.lua -- Scholomance in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Scholomance", {
    name = "Scholomance",
    zone = "Western Plaguelands", territory = "Contested",
    entrance = { map = 1422, x = 70.7, y = 71.0 },
    wings = {
        { bosses = {
            { npc = 10506, name = "Kirtonos the Herald", encounters = { 2805 }, loot = { 16734 }, chance = { 19 } },
            { npc = 10503, name = "Jandice Barov", encounters = { 2804 }, loot = { 16701 }, chance = { 17 } },
            { npc = 11622, name = "Rattlegore", encounters = { 2811 }, loot = { 16711 }, chance = { 18 } },
            { npc = 10433, name = "Marduk Blackpool", encounters = { 2809 } },
            { npc = 10432, name = "Vectus", encounters = { 2813 } },
            { npc = 10508, name = "Ras Frostwhisper", encounters = { 2810 }, loot = { 16689, 14525 }, chance = { 19, 15 } },
            { npc = 10505, name = "Instructor Malicia", encounters = { 2803 }, loot = { 16710, 14623, 14621, 14620, 14622, 14624 }, chance = { 4, 4, 4, 4, 3, 1 } },
            { npc = 11261, name = "Doctor Theolen Krastinov", encounters = { 2802 }, loot = { 16684, 14622, 14620, 14621, 14623, 14624 }, chance = { 8, 4, 4, 4, 4, 1 } },
            { npc = 10901, name = "Lorekeeper Polkelt", encounters = { 2808 }, loot = { 16705, 14620, 14622, 14623, 14621, 14624 }, chance = { 8, 4, 4, 3, 3, 1 } },
            { npc = 10507, name = "The Ravenian", encounters = { 2812 }, loot = { 16716, 14622, 14620, 14623, 14621, 14624 }, chance = { 5, 4, 4, 4, 4, 1 } },
            { npc = 10504, name = "Lord Alexei Barov", encounters = { 2807 }, loot = { 14624, 16722 }, chance = { 7, 4 } },
            { npc = 10502, name = "Lady Illucia Barov", encounters = { 2806 }, loot = { 14620, 14621, 14622, 14623, 14624 }, chance = { 4, 4, 4, 4, 1 } },
            { npc = 1853, name = "Darkmaster Gandling", encounters = { 2801 }, loot = { 16677, 16686, 16731, 16698, 16693, 16720, 16707, 16727, 16667 }, chance = { 13, 13, 12, 12, 12, 11, 11, 6, 5 } },
        } },
    },
})
