-------------------------------------------------------------------------------
--  Data/Dungeons/ShadowfangKeep.lua -- Shadowfang Keep in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ShadowfangKeep", {
    name = "Shadowfang Keep",
    zone = "Silverpine Forest", territory = "Horde",
    entrance = { map = 1421, x = 45.5, y = 67.7 },
    wings = {
        { bosses = {
            { npc = 3914, name = "Rethilgore", encounters = { 2748 }, loot = { 5254, 3194, 273457 }, chance = { 85, 1, 0 } },
            { npc = 3886, name = "Razorclaw the Butcher", encounters = { 2749 }, loot = { 6226, 6633, 1292 }, chance = { 42, 40, 9 } },
            { npc = 3887, name = "Baron Silverlaine", encounters = { 2750 }, loot = { 6323, 6321 }, chance = { 38, 19 } },
            { npc = 4278, name = "Commander Springvale", encounters = { 2751 }, loot = { 3191, 6320, 6341 }, chance = { 34, 29, 9 } },
            { npc = 4279, name = "Odo the Blindwatcher", encounters = { 2752 }, loot = { 6319, 6318 }, chance = { 59, 33 } },
            { npc = 4274, name = "Fenrus the Devourer", encounters = { 2753 }, loot = { 6340, 3230 }, chance = { 74, 18 } },
            { npc = 3927, name = "Wolf Master Nandos", encounters = { 2754 }, loot = { 3748, 6314 }, chance = { 58, 38 } },
            { npc = 4275, name = "Archmage Arugal", encounters = { 2755 }, loot = { 6324, 6392, 6220 }, chance = { 35, 34, 18 } },
            { npc = 3872, name = "Deathsworn Captain", rare = true, loot = { 6641, 6642, 2205 }, chance = { 57, 34, 2 } },
        } },
    },
})
