-------------------------------------------------------------------------------
--  Data/Dungeons/Stockade.lua -- The Stockade in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Stockade", {
    name = "The Stockade",
    zone = "Stormwind City", territory = "Alliance",
    entrance = { map = 1453, x = 51.0, y = 68.1 },
    wings = {
        { bosses = {
            { npc = 1696, name = "Targorr the Dread", encounters = { 2756 }, loot = { 12992 }, chance = { 1 } },
            { npc = 1666, name = "Kam Deepfury", encounters = { 2757 } },
            { npc = 1717, name = "Hamhock", encounters = { 2758 } },
            { npc = 1716, name = "Bazil Thredd", encounters = { 2760 } },
            { npc = 1663, name = "Dextren Ward", encounters = { 2759 } },
            { npc = 1720, name = "Bruegal Ironknuckle", rare = true, loot = { 3228, 2941, 2942 }, chance = { 55, 19, 18 } },
        } },
    },
})
