-------------------------------------------------------------------------------
--  Data/Dungeons/Stratholme.lua -- Stratholme in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Stratholme", {
    name = "Stratholme",
    zone = "Eastern Plaguelands", territory = "Contested",
    entrance = { map = 1423, x = 26.9, y = 11.8 },
    wings = {
        { name = "Main Gate", bosses = {
            { npc = 10808, name = "Timmy the Cruel", encounters = { 474 }, loot = { 13400, 13402, 16724 }, chance = { 21, 20, 13 } },
            { npc = 10516, name = "The Unforgiven", encounters = { 472 }, loot = { 13405, 13404, 16717 }, chance = { 22, 21, 12 } },
            { npc = 10558, name = "Hearthsinger Forresten", encounters = { 473 }, loot = { 16682 }, chance = { 14 } },
            { npc = 10997, name = "Cannon Master Willey", encounters = { 475 }, loot = { 16708 }, chance = { 16 } },
            { npc = 10811, name = "Archivist Galford", encounters = { 477 }, loot = { 13387, 16692 }, chance = { 21, 18 } },
            { npc = 10813, name = "Balnazzar", encounters = { 478 }, loot = { 16725, 18720 } },
            { npc = 10393, name = "Skul", rare = true, encounters = { 2799 } },
            { npc = 10809, name = "Stonespine", rare = true, encounters = { 2800 }, loot = { 13397 }, chance = { 31 } },
        } },
        { name = "Service Entrance", bosses = {
            { npc = 10435, name = "Magistrate Barthilas", encounters = { 482 }, loot = { 18722 }, chance = { 15 } },
            { npc = 10436, name = "Baroness Anastari", encounters = { 479 }, loot = { 16704 }, chance = { 18 } },
            { npc = 10437, name = "Nerub'enkan", encounters = { 480 }, loot = { 16675 }, chance = { 18 } },
            { npc = 10438, name = "Maleki the Pallid", encounters = { 481 }, loot = { 16691 }, chance = { 18 } },
            { npc = 10439, name = "Ramstein the Gorger", encounters = { 483 }, loot = { 16737 }, chance = { 17 } },
            { npc = 10440, name = "Baron Rivendare", encounters = { 484 }, loot = { 13340, 16687, 16732, 16709, 16678, 16694, 16699, 16719, 16728, 16668 }, chance = { 15, 11, 11, 11, 10, 10, 10, 10, 6, 5 } },
        } },
    },
})
