-------------------------------------------------------------------------------
--  Data/Dungeons/SunkenTemple.lua -- Sunken Temple in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("SunkenTemple", {
    name = "Sunken Temple",
    zone = "Swamp of Sorrows", territory = "Contested",
    entrance = { map = 1435, x = 69.6, y = 53.7 },
    wings = {
        { bosses = {
            { npc = 8580, name = "Atal'alarion", encounters = { 3582, 2814 }, loot = { 10799 }, chance = { 18 } },
            { npc = 5721, name = "Dreamscythe", encounters = { 3588, 486 }, loot = { 12465, 12466, 12243 }, chance = { 10, 10, 9 } },
            { npc = 5720, name = "Weaver", encounters = { 3587, 487 }, loot = { 12243, 12466, 12465 }, chance = { 10, 9, 9 } },
            { npc = 5710, name = "Jammal'an the Prophet", encounters = { 3589, 488 }, loot = { 10807 }, chance = { 28 } },
            { npc = 5711, name = "Ogom the Wretched", loot = { 10804 }, chance = { 30 } },
            { npc = 5719, name = "Morphaz", encounters = { 3586, 490 }, loot = { 12466, 12243, 12465 }, chance = { 8, 8, 8 } },
            { npc = 5722, name = "Hazzas", encounters = { 3585, 491 }, loot = { 12466, 12243, 12465 }, chance = { 9, 8, 8 } },
            { npc = 5709, name = "Shade of Eranikus", encounters = { 3584, 493 }, loot = { 10833 }, chance = { 31 } },
            { npc = 8443, name = "Avatar of Hakkar", encounters = { 3583, 492 }, loot = { 10838, 10844 } },
        } },
    },
})
