-------------------------------------------------------------------------------
--  Data/Dungeons/Uldaman.lua -- Uldaman in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Uldaman", {
    name = "Uldaman",
    zone = "Badlands", territory = "Contested",
    entrance = { map = 1418, x = 44.0, y = 12.0 },
    wings = {
        { bosses = {
            { npc = 6910, name = "Revelosh", encounters = { 547 }, loot = { 9389, 9390 }, chance = { 23, 21 } },
            { npc = 7228, name = "Ironaya", encounters = { 549 }, loot = { 9407 }, chance = { 38 } },
            { npc = 7023, name = "Obsidian Sentinel", encounters = { 1887 }, loot = { 9384 }, chance = { 2 } },
            { npc = 7206, name = "Ancient Stone Keeper", encounters = { 551 }, loot = { 9411 }, chance = { 47 } },
            { npc = 7291, name = "Galgann Firehammer", encounters = { 552 } },
            { npc = 4854, name = "Grimlok", encounters = { 553 }, loot = { 9415, 9414, 9416 }, chance = { 39, 29, 19 } },
            { npc = 2748, name = "Archaedas", encounters = { 554 } },
        } },
    },
})
