-------------------------------------------------------------------------------
--  Data/Dungeons/UpperBlackrockSpire.lua -- Upper Blackrock Spire in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("UpperBlackrockSpire", {
    name = "Upper Blackrock Spire",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 41.1, y = 95.3 },
    wings = {
        { bosses = {
            { npc = 9816, name = "Pyroguard Emberseer", encounters = { 3062 }, loot = { 16672 }, chance = { 18 } },
            { npc = 10264, name = "Solakar Flamewreath", loot = { 16695 }, chance = { 18 } },
            { npc = 10899, name = "Goraluk Anvilcrack" },
            { npc = 10339, name = "Gyth", loot = { 12952, 16669 }, chance = { 20, 19 } },
            { npc = 10429, name = "Warchief Rend Blackhand", encounters = { 3063 }, loot = { 16733 }, chance = { 19 } },
            { npc = 10430, name = "The Beast", encounters = { 3068 }, loot = { 16729 }, chance = { 18 } },
            { npc = 10363, name = "General Drakkisath", encounters = { 3069 }, loot = { 13142, 12602, 16700, 16730, 16706, 16674, 16688, 16690, 16721, 16726, 16666 }, chance = { 23, 22, 12, 12, 12, 11, 11, 11, 10, 7, 5 } },
            { npc = 10509, name = "Jed Runewatcher", rare = true },
        } },
    },
})
