-------------------------------------------------------------------------------
--  Data/Dungeons/ZulFarrak.lua -- Zul'Farrak in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ZulFarrak", {
    name = "Zul'Farrak",
    zone = "Tanaris", territory = "Contested",
    entrance = { map = 1446, x = 39.6, y = 21.7 },
    wings = {
        { bosses = {
            { npc = 8127, name = "Antu'sul", encounters = { 595 }, loot = { 9640, 9639, 9379 }, chance = { 32, 18, 2 } },
            { npc = 7272, name = "Theka the Martyr", encounters = { 596 } },
            { npc = 7271, name = "Witch Doctor Zum'rah", encounters = { 597 }, loot = { 18082 }, chance = { 15 } },
            { npc = 7796, name = "Nekrum Gutchewer", encounters = { 598 } },
            { npc = 7275, name = "Shadowpriest Sezz'ziz", encounters = { 599 }, loot = { 9470, 9473, 9475, 9474 }, chance = { 23, 22, 22, 22 } },
            { npc = 7604, name = "Sergeant Bly" },
            { npc = 7795, name = "Hydromancer Velratha", encounters = { 593 } },
            { npc = 7273, name = "Gahz'rilla", encounters = { 594 }, loot = { 9467, 9469 }, chance = { 46, 44 } },
            { npc = 7267, name = "Chief Ukorz Sandscalp", encounters = { 600 }, loot = { 9476, 9477, 11086 }, chance = { 33, 23, 2 } },
            { npc = 10082, name = "Zerillis", rare = true, loot = { 12470 }, chance = { 18 } },
        } },
    },
})
